# -*- coding: utf-8 -*-
"""Embed the project screenshots into previews.js as data URIs.

WebGL refuses to read textures from file:// , so a page opened by double-click
would show empty droplets. Inlining the images sidesteps that: the same file
works from disk, from a local server and from Netlify / GitHub Pages.

Run it after adding or replacing a screenshot in assets/:

    python make-previews.py
"""
import base64, io, os, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
MIME = {".webp": "image/webp", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".png": "image/png", ".svg": "image/svg+xml"}

entries = []
for path in sorted(glob.glob(os.path.join(ROOT, "assets", "*"))):
    name = os.path.basename(path)
    ext = os.path.splitext(path)[1].lower()
    if ext not in MIME or name.startswith("og-"):
        continue  # og-* is the social card, never a droplet texture
    with open(path, "rb") as fh:
        b64 = base64.b64encode(fh.read()).decode("ascii")
    key = "assets/" + name
    entries.append('  "%s":\n    "data:%s;base64,%s"' % (key, MIME[ext], b64))

out = os.path.join(ROOT, "previews.js")
io.open(out, "w", encoding="utf-8", newline="\n").write(
    u"/* Generated by make-previews.py - do not edit by hand.\n"
    u"   Screenshots inlined so the droplets keep their previews even when the\n"
    u"   page is opened straight from disk. Re-run the script after changing\n"
    u"   anything in assets/. */\n"
    u"window.PREVIEWS = {\n" + u",\n".join(entries) + u"\n};\n")

print("wrote previews.js  (%d images, %.0f KB)"
      % (len(entries), os.path.getsize(out) / 1024.0))
